### ISSUE TITLE
CoDA Installation Environment does not work on Ubuntu 20.04 and higher versions.

### ISSUE THREAD

**Issue by auniquesun** [yangcaoai/CoDA_NeurIPS2023#24]
Since Ubuntu 20.04 and higher versions use higher versions of GCC tools, errors occurred when install and  compile the `pointnet2` package.

`/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
error: command '/usr/local/cuda-11.5/bin/nvcc' failed with exit code 1`

![Image](https://github.com/user-attachments/assets/fdae1d25-68a1-4395-b86c-1675c08020dd)

Can authors provide some other ways/ideas to install or use the `pointnet2` package? Thanks very much.

**Comment by yangcaoai** [comment]
Hi thanks for your interests! Sorry, I have deadlines recently and may reply late.  The requirements for dependency versions of PointNet2 is a bit strict, and I haven't found any alternative solutions at the moment. I recommend downgrading your GCC version and trying again.
